"""Add Books table

Revision ID: 080e24511d27
Revises: f3ffe4615512
Create Date: 2022-07-14 20:08:38.379056

"""
import sqlalchemy as sa
from alembic import op
from migrations.tenant import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = "080e24511d27"
down_revision = "f3ffe4615512"
branch_labels = None
depends_on = None


@for_each_tenant_schema
def upgrade(schema: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books", schema=schema)
    # ### end Alembic commands ###
