"""Initial

Revision ID: ec23ff43c7b6
Revises: 
Create Date: 2021-12-28 18:02:08.341009

"""
import sqlalchemy as sa
from alembic import op
from migrations.tenant import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = "ec23ff43c7b6"
down_revision = None
branch_labels = None
depends_on = None




@for_each_tenant_schema
def upgrade(schema: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books", schema=schema)
    # ### end Alembic commands ###
